// <auto-generated />
using System;
using ECommerce.Data.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Data.Migrations
{
    [DbContext(typeof(ECommerceContext))]
    [Migration("20241120222448__init")]
    partial class _init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Data.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsDeleted = false,
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsDeleted = false,
                            Name = "Laptops&Accessories"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsDeleted = false,
                            Name = "SmartWatch"
                        });
                });

            modelBuilder.Entity("ECommerce.Data.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Samsung",
                            CategoryId = 1,
                            Description = "Experience epic performance with the Galaxy S23 Ultra. Features a 200MP camera, long battery life, and sleek design.",
                            ISBN = "MOB123456",
                            IsDeleted = false,
                            ListPrice = 1200.0,
                            Price = 1100.0,
                            Price100 = 1000.0,
                            Price50 = 1050.0,
                            Title = "Galaxy S23 Ultra"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sony",
                            CategoryId = 2,
                            Description = "Industry-leading noise-canceling headphones with superior sound quality, 30-hour battery life, and a comfortable design.",
                            ISBN = "ELEC789012",
                            IsDeleted = false,
                            ListPrice = 400.0,
                            Price = 350.0,
                            Price100 = 330.0,
                            Price50 = 340.0,
                            Title = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Dell",
                            CategoryId = 3,
                            Description = "The Dell XPS 15 offers a stunning InfinityEdge display, powerful performance with Intel i9, and sleek aluminum chassis.",
                            ISBN = "LAP345678",
                            IsDeleted = false,
                            ListPrice = 2000.0,
                            Price = 1900.0,
                            Price100 = 1800.0,
                            Price50 = 1850.0,
                            Title = "Dell XPS 15"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Apple",
                            CategoryId = 4,
                            Description = "Track your health and fitness with the Apple Watch Series 9. Features an always-on display, advanced sensors, and seamless integration with iPhone.",
                            ISBN = "SWATCH901234",
                            IsDeleted = false,
                            ListPrice = 500.0,
                            Price = 470.0,
                            Price100 = 430.0,
                            Price50 = 450.0,
                            Title = "Apple Watch Series 9"
                        });
                });

            modelBuilder.Entity("ECommerce.Data.Entity.Product", b =>
                {
                    b.HasOne("ECommerce.Data.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Data.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
